import axiosInstance from "../api/axiosInstance";

export const publicationService = {
  listMyPublications: (params) => axiosInstance.get("/publications/mine", { params }),
  getMyPublication: (id) => axiosInstance.get(`/publications/mine/${id}`),
  getWorldManagement: (id) => axiosInstance.get(`/publications/mine/${id}/world-management`),
  updateWorldManagement: (id, payload) => axiosInstance.patch(`/publications/mine/${id}/world-management`, payload),
  getWorldPricing: (id) => axiosInstance.get(`/publications/mine/${id}/world-pricing`),
  updateWorldPricing: (id, monthlyStars) => axiosInstance.patch(`/publications/mine/${id}/world-pricing`, { monthlyStars }),
  uploadWorldCover: (id, file, onProgress) => { const body = new FormData(); body.append("file", file); return axiosInstance.post(`/publications/mine/${id}/world-management/cover`, body, { onUploadProgress: (event) => onProgress?.(event.total ? Math.round(event.loaded * 100 / event.total) : 0) }); },
  uploadWorldStory: (id, file, fields = {}, onProgress) => { const body = new FormData(); body.append("file", file); Object.entries(fields).forEach(([key, value]) => body.append(key, value)); return axiosInstance.post(`/publications/mine/${id}/world-management/stories`, body, { onUploadProgress: (event) => onProgress?.(event.total ? Math.round(event.loaded * 100 / event.total) : 0) }); },
  includeWorldExperience: (id, experienceId) => axiosInstance.post(`/publications/mine/${id}/world-management/experiences/${encodeURIComponent(experienceId)}`),
  removeWorldExperience: (id, experienceId) => axiosInstance.delete(`/publications/mine/${id}/world-management/experiences/${encodeURIComponent(experienceId)}`),
  openWorldWave: (id) => axiosInstance.post(`/publications/mine/${id}/world-management/waves`),
  getWorldModerators: (id) => axiosInstance.get(`/publications/mine/${id}/world-management/moderators`),
  getWorldModeratorCandidates: (id, params) => axiosInstance.get(`/publications/mine/${id}/world-management/moderator-candidates`, { params }),
  addWorldModerator: (id, userId) => axiosInstance.post(`/publications/mine/${id}/world-management/moderators`, { userId }),
  removeWorldModerator: (id, userId) => axiosInstance.delete(`/publications/mine/${id}/world-management/moderators/${encodeURIComponent(userId)}`),
  createPublicationDraft: (payload) => axiosInstance.post("/publications/drafts", payload),
  updatePublicationDraft: (id, payload) => axiosInstance.put(`/publications/mine/${id}`, payload),
  setCommentsEnabled: (id, enabled) => axiosInstance.put(`/publications/mine/${id}/comments-enabled`, { enabled }),
  addChapter: (id, payload) => axiosInstance.post(`/publications/mine/${id}/chapters`, payload),
  updateChapter: (id, chapterId, payload) => axiosInstance.put(`/publications/mine/${id}/chapters/${chapterId}`, payload),
  deleteChapter: (id, chapterId, statusVersion) => axiosInstance.delete(`/publications/mine/${id}/chapters/${chapterId}`, { data: { statusVersion } }),
  reorderChapters: (id, chapterIds, statusVersion) => axiosInstance.post(`/publications/mine/${id}/reorder-chapters`, { chapterIds, statusVersion }),
  uploadMedia: (id, file, fields, onProgress) => { const body = new FormData(); body.append("file", file); Object.entries(fields).forEach(([key, value]) => body.append(key, value)); return axiosInstance.post(`/publications/mine/${id}/media-upload`, body, { onUploadProgress: (event) => onProgress?.(event.total ? Math.round(event.loaded * 100 / event.total) : 0) }); },
  deleteMedia: (id, purpose, statusVersion) => axiosInstance.delete(`/publications/mine/${id}/media/${purpose}`, { data: { statusVersion } }),
  submitPublication: (id, statusVersion) => axiosInstance.post(`/publications/mine/${id}/submit`, { statusVersion }),
  resubmitPublication: (id, statusVersion) => axiosInstance.post(`/publications/mine/${id}/resubmit`, { statusVersion }),
  startPublishedRevision: (id, statusVersion) => axiosInstance.post(`/publications/mine/${id}/start-revision`, { statusVersion }),
  cancelPublishedRevision: (id, statusVersion) => axiosInstance.post(`/publications/mine/${id}/cancel-revision`, { statusVersion }),
  archivePublication: (id, statusVersion) => axiosInstance.post(`/publications/mine/${id}/archive`, { statusVersion }),
  pinSeen: (id, pinned, statusVersion) => axiosInstance.put(`/publications/mine/${id}/pin`, { pinned, statusVersion }),
  deleteSeen: (id, statusVersion) => axiosInstance.delete(`/publications/mine/${id}/seen`, { data: { statusVersion } }),
  getSeenInsights: (id) => axiosInstance.get(`/publications/mine/${id}/insights`),
  deletePlanet: (id, statusVersion) => axiosInstance.delete(`/publications/mine/${id}`, { data: { statusVersion } }),
  listSeenCategories: () => axiosInstance.get("/publications/seen/categories"),
  listMySeries: () => axiosInstance.get("/publications/series"),
  getSeries: (seriesId) => axiosInstance.get(`/publications/series/${encodeURIComponent(seriesId)}`),
  createSeries: (payload) => axiosInstance.post("/publications/series", typeof payload === "string" ? { name: payload } : payload),
  updateSeries: (seriesId, payload) => axiosInstance.patch(`/publications/series/${encodeURIComponent(seriesId)}`, payload),
  deleteSeries: (seriesId) => axiosInstance.delete(`/publications/series/${encodeURIComponent(seriesId)}`),
  addSeenToSeries: (seriesId, seenId) => axiosInstance.post(`/publications/series/${encodeURIComponent(seriesId)}/seens/${encodeURIComponent(seenId)}`),
  removeSeenFromSeries: (seriesId, seenId) => axiosInstance.delete(`/publications/series/${encodeURIComponent(seriesId)}/seens/${encodeURIComponent(seenId)}`),
  listPublishedSeens: (params) => axiosInstance.get("/publications/seen", { params }),
  getPublicPublication: (id, params) => axiosInstance.get(`/publications/${id}`, { params }),
  markWorldWalked: (id) => axiosInstance.post(`/publications/${id}/walked`),
  listWorldWalkers: (id, params) => axiosInstance.get(`/publications/${id}/walkers`, { params }),
  getPoll: (id, chapterId, blockId) => axiosInstance.get(`/publications/${id}/chapters/${chapterId}/polls/${blockId}`),
  votePoll: (id, chapterId, blockId, optionIndex) => axiosInstance.put(`/publications/${id}/chapters/${chapterId}/polls/${blockId}`, { optionIndex }),
  getSeenEngagement: (id, params) => axiosInstance.get(`/publications/${id}/engagement`, { params }),
  listSeenReactors: (id, params) => axiosInstance.get(`/publications/${id}/reactions`, { params }),
  reactToSeen: (id, reaction, accessToken = "") => axiosInstance.put(`/publications/${id}/reaction`, { reaction, accessToken }),
  removeSeenReaction: (id, accessToken = "") => axiosInstance.delete(`/publications/${id}/reaction`, { data: { accessToken } }),
  commentOnSeen: (id, text, accessToken = "", parentCommentId = "") => axiosInstance.post(`/publications/${id}/comments`, { text, accessToken, parentCommentId: parentCommentId || undefined }),
  removeSeenComment: (id, commentId) => axiosInstance.delete(`/publications/${id}/comments/${encodeURIComponent(commentId)}`),
  reactToSeenComment: (id, commentId, reaction, accessToken = "") => axiosInstance.put(`/publications/${id}/comments/${commentId}/reaction`, { reaction, accessToken }),
  removeSeenCommentReaction: (id, commentId, accessToken = "") => axiosInstance.delete(`/publications/${id}/comments/${commentId}/reaction`, { data: { accessToken } }),
  shareSeen: (id, caption = "", accessToken = "") => axiosInstance.put(`/publications/${id}/share`, { caption, accessToken }),
  removeSeenShare: (id, accessToken = "") => axiosInstance.delete(`/publications/${id}/share`, { data: { accessToken } }),
  toggleSeenSave: (id, accessToken = "") => axiosInstance.put(`/publications/${id}/save`, { accessToken }),
  hideSeen: (id, reason = "NOT_INTERESTED") => axiosInstance.post(`/publications/${id}/hide`, { reason }),
  muteSeenCreator: (id, reason = "MUTED_FROM_SEEN") => axiosInstance.post(`/publications/${id}/mute-creator`, { reason }),
  blockSeenCreator: (id) => axiosInstance.put(`/publications/${id}/block-creator`),
  reportSeen: (id, payload) => axiosInstance.post(`/publications/${id}/report`, payload),
};
