import axiosInstance from "../api/axiosInstance";

export const publicationService = {
  listMyPublications: (params) => axiosInstance.get("/publications/mine", { params }),
  getMyPublication: (id) => axiosInstance.get(`/publications/mine/${id}`),
  createPublicationDraft: (payload) => axiosInstance.post("/publications/drafts", payload),
  updatePublicationDraft: (id, payload) => axiosInstance.put(`/publications/mine/${id}`, payload),
  addChapter: (id, payload) => axiosInstance.post(`/publications/mine/${id}/chapters`, payload),
  updateChapter: (id, chapterId, payload) => axiosInstance.put(`/publications/mine/${id}/chapters/${chapterId}`, payload),
  deleteChapter: (id, chapterId, statusVersion) => axiosInstance.delete(`/publications/mine/${id}/chapters/${chapterId}`, { data: { statusVersion } }),
  reorderChapters: (id, chapterIds, statusVersion) => axiosInstance.post(`/publications/mine/${id}/reorder-chapters`, { chapterIds, statusVersion }),
  uploadMedia: (id, file, fields, onProgress) => { const body = new FormData(); body.append("file", file); Object.entries(fields).forEach(([key, value]) => body.append(key, value)); return axiosInstance.post(`/publications/mine/${id}/media-upload`, body, { onUploadProgress: (event) => onProgress?.(event.total ? Math.round(event.loaded * 100 / event.total) : 0) }); },
  deleteMedia: (id, purpose, statusVersion) => axiosInstance.delete(`/publications/mine/${id}/media/${purpose}`, { data: { statusVersion } }),
  submitPublication: (id, statusVersion) => axiosInstance.post(`/publications/mine/${id}/submit`, { statusVersion }),
  resubmitPublication: (id, statusVersion) => axiosInstance.post(`/publications/mine/${id}/resubmit`, { statusVersion }),
  startPublishedRevision: (id, statusVersion) => axiosInstance.post(`/publications/mine/${id}/start-revision`, { statusVersion }),
  cancelPublishedRevision: (id, statusVersion) => axiosInstance.post(`/publications/mine/${id}/cancel-revision`, { statusVersion }),
  archivePublication: (id, statusVersion) => axiosInstance.post(`/publications/mine/${id}/archive`, { statusVersion }),
  deletePlanet: (id, statusVersion) => axiosInstance.delete(`/publications/mine/${id}`, { data: { statusVersion } }),
  listPublishedSeens: (params) => axiosInstance.get("/publications/seen", { params }),
  getPublicPublication: (id) => axiosInstance.get(`/publications/${id}`),
  markWorldWalked: (id) => axiosInstance.post(`/publications/${id}/walked`),
  getSeenEngagement: (id) => axiosInstance.get(`/publications/${id}/engagement`),
  reactToSeen: (id, reaction) => axiosInstance.put(`/publications/${id}/reaction`, { reaction }),
  removeSeenReaction: (id) => axiosInstance.delete(`/publications/${id}/reaction`),
  commentOnSeen: (id, text) => axiosInstance.post(`/publications/${id}/comments`, { text }),
  shareSeen: (id, caption = "") => axiosInstance.put(`/publications/${id}/share`, { caption }),
  removeSeenShare: (id) => axiosInstance.delete(`/publications/${id}/share`),
  toggleSeenSave: (id) => axiosInstance.put(`/publications/${id}/save`),
  hideSeen: (id, reason = "NOT_INTERESTED") => axiosInstance.post(`/publications/${id}/hide`, { reason }),
  muteSeenCreator: (id, reason = "MUTED_FROM_SEEN") => axiosInstance.post(`/publications/${id}/mute-creator`, { reason }),
  blockSeenCreator: (id) => axiosInstance.put(`/publications/${id}/block-creator`),
  reportSeen: (id, payload) => axiosInstance.post(`/publications/${id}/report`, payload),
};
