import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { FiCheck, FiGift, FiTrash2, FiX } from "react-icons/fi";
import { dreamService } from "../../services/dreamService";
import { createIdempotencyKey } from "../../utils/idempotencyKey";

const GOALS = [500, 900, 1500, 2500, 5000];
const giftEmoji = { rain: "💙", iloveyou: "❤️", selfie: "✨", glow: "🌟", shopping: "🛍️", fit: "💪", ufo: "🛸", pop: "🎉", rocket: "🚀", gold: "🏆", bath: "💎", summit: "🏔️", bugatti: "🏎️", lambo: "🔥", throne: "👑", crown: "♛" };

function Editor({ dream, onClose, onSaved }) {
  const [form, setForm] = useState({ emoji: dream?.emoji || "✨", title: dream?.title || "", reason: dream?.reason || "", goalStars: dream?.goalStars || 900, version: dream?.version });
  const [saving, setSaving] = useState(false), [error, setError] = useState("");
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await dreamService.saveMine(form); onSaved(response.data.data.dream); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to save Dream"); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-[80] grid place-items-end bg-black/70 p-0 sm:place-items-center sm:p-5" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><form className="w-full max-w-lg rounded-t-3xl border border-atseen-line bg-atseen-surface p-6 sm:rounded-3xl" onSubmit={save}><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">✨ My Dream</h2><p className="mt-1 text-xs text-atseen-muted">One real experience you dream of doing next.</p></div><button onClick={onClose} type="button"><FiX /></button></div><label className="mt-5 block text-[10px] font-black uppercase tracking-widest text-atseen-muted">What’s the dream?</label><div className="mt-2 flex gap-2"><input className="w-14 rounded-xl border border-atseen-line bg-atseen-bg p-3 text-center" maxLength={16} onChange={(event) => setForm({ ...form, emoji: event.target.value })} value={form.emoji} /><input className="min-w-0 flex-1 rounded-xl border border-atseen-line bg-atseen-bg p-3" maxLength={40} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Learn surfing" required value={form.title} /></div><label className="mt-4 block text-[10px] font-black uppercase tracking-widest text-atseen-muted">Why it matters</label><textarea className="mt-2 w-full rounded-xl border border-atseen-line bg-atseen-bg p-3" maxLength={120} onChange={(event) => setForm({ ...form, reason: event.target.value })} placeholder="One honest line…" required rows={3} value={form.reason} /><label className="mt-4 block text-[10px] font-black uppercase tracking-widest text-atseen-muted">Star goal</label><div className="mt-2 flex flex-wrap gap-2">{GOALS.map((goal) => <button className={`rounded-full border px-4 py-2 text-xs font-bold ${form.goalStars === goal ? "border-atseen-blue bg-atseen-blue/10 text-atseen-blue" : "border-atseen-line text-atseen-muted"}`} key={goal} onClick={() => setForm({ ...form, goalStars: goal })} type="button">✦{goal.toLocaleString()}</button>)}</div><p className="mt-3 text-[10px] text-atseen-muted">Supporters send gifts from their Stars balance. Every Star goes toward the Dream.</p>{error ? <p className="mt-3 text-xs text-red-400">{error}</p> : null}<button className="mt-5 w-full rounded-xl bg-atseen-blue p-3 font-black text-atseen-bg disabled:opacity-50" disabled={saving} type="submit">{saving ? "Saving…" : dream ? "Save Dream" : "Light the Dream ✦"}</button></form></div>;
}

function GiftPicker({ dream, gifts, onClose, onSent }) {
  const queryClient = useQueryClient();
  const [privateSupport, setPrivateSupport] = useState(false), [sending, setSending] = useState(""), [sent, setSent] = useState(null), [error, setError] = useState("");
  const send = async (gift) => { if (sending || sent) return; setSending(gift.key); setError(""); try { const response = await dreamService.sendGift(dream.id, { giftKey: gift.key, privateSupport, idempotencyKey: createIdempotencyKey("dream-gift") }); const result = response.data.data; queryClient.setQueryData(["wallet"], result.wallet); await queryClient.invalidateQueries({ queryKey: ["wallet-ledger"] }); setSent(gift); onSent(result.dream); setTimeout(onClose, 1100); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to send gift"); } finally { setSending(""); } };
  return <div className="fixed inset-0 z-[80] grid place-items-end bg-black/70 sm:place-items-center sm:p-5" onMouseDown={(event) => event.target === event.currentTarget && !sending && onClose()}><div className="relative max-h-[88vh] w-full max-w-xl overflow-y-auto rounded-t-3xl border border-atseen-line bg-atseen-surface p-6 sm:rounded-3xl">{sent ? <div className="absolute inset-0 z-10 grid place-items-center bg-atseen-surface/95 p-8 text-center"><div><span className="text-6xl">{giftEmoji[sent.key] || "✦"}</span><h2 className="mt-4 text-xl font-black">{sent.name} sent!</h2><p className="mt-2 text-sm text-atseen-muted">✦{sent.stars.toLocaleString()} was added to this Dream.</p></div></div> : null}<div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Help Make It Happen</h2><p className="mt-1 text-xs text-atseen-muted">Tap a gift to send it instantly to {dream.title}.</p></div><button disabled={Boolean(sending)} onClick={onClose} type="button"><FiX /></button></div><div className="mt-5 grid grid-cols-4 gap-2">{gifts.map((gift) => <button className={`rounded-2xl bg-white/[.035] p-3 text-center transition active:scale-95 disabled:opacity-40 ${sending === gift.key ? "border border-atseen-blue bg-atseen-blue/10" : ""}`} disabled={Boolean(sending)} key={gift.key} onClick={() => send(gift)} type="button"><span className="text-2xl">{giftEmoji[gift.key] || "✦"}</span><strong className="mt-2 block truncate text-[10px]">{sending === gift.key ? "Sending…" : gift.name}</strong><small className="mt-1 block text-atseen-muted">✦{gift.stars.toLocaleString()}</small></button>)}</div><label className="mt-5 flex items-center gap-3 text-xs text-atseen-muted"><input checked={privateSupport} disabled={Boolean(sending)} onChange={(event) => setPrivateSupport(event.target.checked)} type="checkbox" /> Support privately</label>{error ? <div className="mt-4 rounded-xl bg-red-400/10 p-3 text-xs text-red-300">{error}{error.toLowerCase().includes("insufficient") ? <Link className="ml-2 font-bold underline" to="/wallet">Open wallet</Link> : null}</div> : null}</div></div>;
}

export default function ProfileDream({ capabilities, profile, role }) {
  const [editor, setEditor] = useState(false), [picker, setPicker] = useState(false);
  const query = useQuery({ queryKey: ["creator-dream", profile?.username], queryFn: () => dreamService.getCreatorDream(profile.username).then((response) => response.data.data), enabled: role === "creator" && Boolean(profile?.username), retry: false });
  if (role !== "creator" || query.isLoading || query.isError) return null;
  const dream = query.data?.dream, gifts = query.data?.gifts || [];
  if (!dream && !capabilities.isOwner) return null;
  const progress = dream ? Math.min(100, Math.round((dream.receivedStars / dream.goalStars) * 100)) : 0;
  const update = (next) => { query.refetch(); setEditor(false); setPicker(false); if (next) query.refetch(); };
  const status = async (action) => { if (!confirm(action === "complete" ? "Mark this Dream as completed?" : "Remove this Dream?")) return; try { await (action === "complete" ? dreamService.completeMine(dream.id, dream.version) : dreamService.removeMine(dream.id, dream.version)); update(); } catch { query.refetch(); } };
  return <section className="mt-5 rounded-3xl border border-atseen-blue/20 bg-gradient-to-br from-atseen-blue/[.08] to-atseen-surface p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.18em] text-atseen-blue">✨ My Dream</p>{capabilities.isOwner ? <button className="text-xs font-bold text-atseen-blue" onClick={() => setEditor(true)} type="button">{dream ? "Edit" : "Add yours"}</button> : null}</div>{dream ? <><div className="mt-4 flex gap-3"><span className="grid h-12 w-12 flex-none place-items-center rounded-2xl bg-atseen-blue/10 text-2xl">{dream.emoji}</span><div className="min-w-0"><h2 className="font-black">{dream.title}</h2><p className="mt-1 text-sm leading-5 text-atseen-muted">{dream.reason}</p></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-gradient-to-r from-atseen-blue to-white" style={{ width: `${progress}%` }} /></div><div className="mt-2 flex justify-between text-[11px] text-atseen-muted"><span>✦{dream.receivedStars.toLocaleString()} of ✦{dream.goalStars.toLocaleString()}</span><span>{dream.supporterCount} supporters · {progress}%</span></div>{dream.status === "COMPLETED" ? <p className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-green-400"><FiCheck /> Dream completed</p> : capabilities.isOwner ? <div className="mt-4 flex gap-4"><button className="text-xs font-bold text-green-400" onClick={() => status("complete")} type="button"><FiCheck className="inline" /> Mark completed</button><button className="text-xs font-bold text-red-400" onClick={() => status("remove")} type="button"><FiTrash2 className="inline" /> Remove</button></div> : <button className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-full border border-atseen-blue/30 bg-atseen-blue/10 p-3 text-sm font-black text-atseen-blue" onClick={() => setPicker(true)} type="button"><FiGift /> Help Make It Happen</button>}{dream.supporters?.length ? <div className="mt-4 border-t border-atseen-line pt-3"><p className="text-[10px] text-atseen-muted">Recent supporters</p><div className="mt-2 flex -space-x-2">{dream.supporters.slice(0, 6).map((supporter, index) => supporter.avatar ? <img alt={supporter.name} className="h-8 w-8 rounded-full border-2 border-atseen-surface object-cover" key={`${supporter.username}-${index}`} src={supporter.avatar} /> : <span className="grid h-8 w-8 place-items-center rounded-full border-2 border-atseen-surface bg-atseen-bg text-[10px]" key={`${supporter.username}-${index}`}>{supporter.name?.slice(0, 1)}</span>)}</div></div> : null}</> : <p className="mt-3 text-sm text-atseen-muted">One real experience you dream of doing next.</p>}{editor ? <Editor dream={dream?.status === "ACTIVE" ? dream : null} onClose={() => setEditor(false)} onSaved={update} /> : null}{picker ? <GiftPicker dream={dream} gifts={gifts} onClose={() => setPicker(false)} onSent={() => query.refetch()} /> : null}</section>;
}
