import { Link } from "react-router-dom";
import PlanetSlot from "./PlanetSlot";
import { resolveMediaUrl } from "../../utils/media";

export default function ProfileOrbit({ capabilities, planets = [], profile, role }) {
  if (role !== "creator" || (!planets.length && !capabilities.isOwner)) return null;
  const bySlot = Object.fromEntries(planets.map((planet) => [planet.planet?.slot, planet]));
  const visible = [bySlot.WORLD_1, bySlot.WORLD_2, bySlot.PREMIUM].filter(Boolean);
  return <section className="profile-planet-orbit"><div className="profile-orbit-heading"><div><p className="profile-orbit-overline">Orbit</p><h2>{capabilities.isOwner ? "Your worlds" : `${profile?.displayName || "Creator"}’s worlds`}</h2></div>{capabilities.isOwner ? <Link to="/studio/worlds">Manage</Link> : null}</div><div className="profile-orbit-sky" aria-label="Creator World orbit"><div className="profile-orbit-stars" /><div className="profile-orbit-ring ring-one"/><div className="profile-orbit-ring ring-two"/><div className="profile-orbit-person">{profile?.avatar ? <img alt={profile.displayName} src={resolveMediaUrl(profile.avatar)} /> : <span>{profile?.displayName?.slice(0,1) || "@"}</span>}<small>@{profile?.username}</small></div><div className="profile-orbit-position position-left"><PlanetSlot compact owner={capabilities.isOwner} planet={bySlot.WORLD_1} /></div><div className="profile-orbit-position position-right"><PlanetSlot compact owner={capabilities.isOwner} planet={bySlot.WORLD_2} /></div><div className="profile-orbit-position position-front"><PlanetSlot compact owner={capabilities.isOwner} planet={bySlot.PREMIUM} premium /></div></div>{visible.length ? <div className="profile-world-list">{visible.map((planet) => <article className="profile-world-card" key={planet.id}>{planet.coverMedia?.secureUrl ? <Link className="profile-world-cover" to={`/world/${planet.id}`}><img alt="" src={planet.coverMedia.secureUrl} /><span>{planet.planet?.emoji || "🪐"}</span></Link> : null}<PlanetSlot planet={planet} premium={planet.kind === "PREMIUM_WORLD"} /></article>)}</div> : <p className="profile-orbit-empty">Light a planet to place your first World in Orbit.</p>}<p className="profile-orbit-whisper">{capabilities.isOwner ? "Published Worlds are visible to fans here." : "Tap a planet to step inside."}</p></section>;
}
