import { useRef, useState } from "react";
import { Link } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FiBookmark, FiChevronDown, FiMessageCircle, FiShare2 } from "react-icons/fi";
import FanAvatar from "../shared/FanAvatar";
import FanModal from "../shared/FanModal";
import VerifiedBadge from "../shared/VerifiedBadge";
import { wallService } from "../../../services/wallService";

const labels = { RIGHT_NOW: "⚡ Right now", COFFEE: "☕ Coffee", NEED_HELP: "🆘 Need help", PLACE: "📍 Place", RESTAURANT: "🍜 Restaurant", BOOK: "📚 Book", MOVIE: "🎬 Movie", TRAVEL: "✈️ Travel", BUSINESS: "💼 Business", FITNESS: "💪 Fitness", WELLNESS: "🌿 Wellness", LIFESTYLE: "✨ Lifestyle", BEAUTY: "💄 Beauty" };
const message = (error) => error.response?.status === 403 ? "This social action is not available for your account." : error.response?.data?.message || "Unable to complete this action.";
const reactions = {
  like: { emoji: "👍", label: "Like", color: "text-blue-400" },
  love: { emoji: "❤️", label: "Love", color: "text-rose-400" },
  care: { emoji: "🥰", label: "Care", color: "text-amber-300" },
  haha: { emoji: "😂", label: "Haha", color: "text-yellow-300" },
  wow: { emoji: "😮", label: "Wow", color: "text-yellow-300" },
  sad: { emoji: "😢", label: "Sad", color: "text-yellow-300" },
  angry: { emoji: "😡", label: "Angry", color: "text-orange-400" },
};

export default function FeedPost({ post }) {
  const postId = post.originalPostId || post.id;
  const shareId = post.shareId || undefined;
  const queryClient = useQueryClient();
  const [commentsOpen, setCommentsOpen] = useState(false);
  const [reactionsOpen, setReactionsOpen] = useState(false);
  const [reactionFilter, setReactionFilter] = useState("all");
  const [shareOpen, setShareOpen] = useState(false);
  const [shareCaption, setShareCaption] = useState("");
  const [text, setText] = useState("");
  const [error, setError] = useState("");
  const [reactionPickerOpen, setReactionPickerOpen] = useState(false);
  const reactionCloseTimer = useRef();
  const openReactionPicker = () => {
    window.clearTimeout(reactionCloseTimer.current);
    setReactionPickerOpen(true);
  };
  const scheduleReactionPickerClose = () => {
    window.clearTimeout(reactionCloseTimer.current);
    reactionCloseTimer.current = window.setTimeout(() => setReactionPickerOpen(false), 250);
  };
  const commentsQuery = useQuery({ queryKey: ["wall-comments", postId, shareId || "original"], queryFn: () => wallService.comments(postId, shareId).then((response) => response.data.data.comments || []), enabled: commentsOpen, retry: false });
  const reactionsQuery = useQuery({ queryKey: ["wall-reactions", postId, shareId || "original"], queryFn: () => wallService.reactions(postId, shareId).then((response) => response.data.data), enabled: reactionsOpen, retry: false });
  const updatePost = (engagement) => queryClient.setQueryData(["wall-posts"], (items = []) => items.map((item) => item.id === post.id ? { ...item, ...engagement } : item));
  const react = useMutation({ mutationFn: (reaction) => wallService.react(postId, reaction, shareId), onSuccess: (response) => { setError(""); setReactionPickerOpen(false); updatePost(response.data.data.engagement); }, onError: (requestError) => setError(message(requestError)) });
  const share = useMutation({ mutationFn: () => wallService.share(postId, shareCaption.trim()), onSuccess: (response) => { setError(""); setShareOpen(false); setShareCaption(""); updatePost(response.data.data.engagement); queryClient.invalidateQueries({ queryKey: ["unified-profile"] }); queryClient.invalidateQueries({ queryKey: ["wall-posts"] }); }, onError: (requestError) => setError(message(requestError)) });
  const save = useMutation({ mutationFn: () => wallService.save(postId, shareId), onSuccess: (response) => { setError(""); updatePost(response.data.data.engagement); queryClient.invalidateQueries({ queryKey: ["saved-content"] }); }, onError: (requestError) => setError(message(requestError)) });
  const comment = useMutation({ mutationFn: () => wallService.comment(postId, text.trim(), shareId), onSuccess: async (response) => { setText(""); setError(""); updatePost(response.data.data.engagement); await commentsQuery.refetch(); }, onError: (requestError) => setError(message(requestError)) });

  return <>
    <article className="border-b border-white/[0.05] py-[18px]">
      {post.sharedBy ? <div className="mb-3 flex items-center gap-2 text-[11px] text-atseen-muted"><FiShare2 className="text-atseen-blue" /><Link className="font-bold text-atseen-text" to={`/profile/${post.sharedBy.username}`}>{post.sharedBy.name}</Link><span>shared this · {new Date(post.feedCreatedAt).toLocaleString()}</span></div> : null}
      {post.shareCaption ? <div className="mb-4 rounded-2xl border border-atseen-blue/15 bg-atseen-blue/[0.06] p-4"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-atseen-blue">Shared with a note</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-white/90">{post.shareCaption}</p></div> : null}
      <div className="flex items-center gap-2.5"><Link to={`/profile/${post.creator.username}`}><FanAvatar name={post.creator.name} size="h-[38px] w-[38px]" src={post.creator.avatar} /></Link><div className="min-w-0"><Link className="flex items-center gap-1 truncate text-[13.5px] font-bold" to={`/profile/${post.creator.username}`}>{post.creator.name}{post.creator.verified ? <VerifiedBadge /> : null}</Link><p className="text-[10.5px] text-atseen-muted">{new Date(post.createdAt).toLocaleString()}{post.location ? ` · ${post.location}` : ""}</p></div><span className="ml-auto rounded-full border border-atseen-blue/20 bg-atseen-blue/10 px-2.5 py-1 text-[10px] font-bold text-atseen-blue">{labels[post.context] || labels.RIGHT_NOW}</span></div>
      <p className="mt-2.5 whitespace-pre-wrap text-sm leading-7 text-white/90">{post.text}</p>
      {post.media?.length ? <div className="mt-3 grid gap-2">{post.media.map((item) => <img alt="Wall post" className="max-h-[520px] w-full rounded-2xl object-cover" key={item.assetId} src={item.url} />)}</div> : null}
      {post.reactionCount ? <button className="mt-3 flex items-center gap-2 text-[11px] text-atseen-muted transition hover:text-white" onClick={() => { setReactionFilter("all"); setReactionsOpen(true); }} type="button"><span aria-label="Top reactions" className="flex -space-x-1">{(post.topReactions || ["like"]).map((type) => <span className="grid h-5 w-5 place-items-center rounded-full border border-atseen-bg bg-atseen-surface-2 text-[12px]" key={type} title={reactions[type]?.label}>{reactions[type]?.emoji}</span>)}</span><span className="hover:underline">{post.reactionCount.toLocaleString()} {post.reactionCount === 1 ? "reaction" : "reactions"}</span></button> : null}
      <div className="mt-3 flex items-center gap-5 border-t border-white/[0.05] pt-3 text-[11.5px] font-semibold text-atseen-dim"><div className="relative flex items-center" onMouseEnter={openReactionPicker} onMouseLeave={scheduleReactionPickerClose}>{reactionPickerOpen ? <div className="absolute bottom-full left-0 z-20 mb-2 flex items-end gap-1 rounded-full border border-white/10 bg-atseen-surface px-2 py-1.5 shadow-2xl shadow-black/50" onMouseEnter={openReactionPicker} onMouseLeave={scheduleReactionPickerClose} role="menu">{Object.entries(reactions).map(([type, details]) => <button aria-label={`React ${details.label}`} className="group relative grid h-9 w-9 place-items-center rounded-full text-2xl transition hover:-translate-y-1 hover:scale-125 focus:-translate-y-1 focus:scale-125 focus:outline-none" disabled={react.isPending} key={type} onClick={() => react.mutate(type)} role="menuitem" title={details.label} type="button"><span>{details.emoji}</span><span className="pointer-events-none absolute -top-7 hidden rounded bg-black/90 px-1.5 py-0.5 text-[9px] font-bold text-white group-hover:block group-focus:block">{details.label}</span></button>)}</div> : null}<button className={`inline-flex items-center gap-1.5 ${post.viewerReaction ? reactions[post.viewerReaction]?.color : ""}`} disabled={react.isPending} onClick={() => react.mutate(post.viewerReaction || "like")} type="button"><span className="text-base">{post.viewerReaction ? reactions[post.viewerReaction]?.emoji : "👍"}</span>{post.viewerReaction ? reactions[post.viewerReaction]?.label : "Like"}</button><button aria-expanded={reactionPickerOpen} aria-label="Choose a reaction" className="ml-1 grid h-6 w-5 place-items-center rounded hover:bg-white/5" onClick={() => setReactionPickerOpen((open) => !open)} type="button"><FiChevronDown /></button></div><button className="inline-flex items-center gap-1.5" onClick={() => setCommentsOpen(true)} type="button"><FiMessageCircle />{post.commentCount}</button><button className={`inline-flex items-center gap-1.5 ${post.viewerShared ? "text-atseen-blue" : ""}`} disabled={share.isPending} onClick={() => post.viewerShared ? share.mutate() : setShareOpen(true)} type="button"><FiShare2 />{post.viewerShared ? "Shared" : "Share"} · {post.shareCount}</button><button aria-label={post.viewerSaved ? "Remove Wall post from Saved" : "Save Wall post"} className={`ml-auto inline-flex items-center ${post.viewerSaved ? "text-atseen-blue" : ""}`} disabled={save.isPending} onClick={() => save.mutate()} type="button"><FiBookmark fill={post.viewerSaved ? "currentColor" : "none"} /></button></div>
      {error ? <p className="mt-3 text-xs text-red-300">{error}</p> : null}
    </article>
    <FanModal isOpen={reactionsOpen} onClose={() => setReactionsOpen(false)} title={`Reactions · ${post.reactionCount}`}>
      {reactionsQuery.isLoading ? <p className="py-8 text-center text-sm text-atseen-muted">Loading reactions…</p> : reactionsQuery.isError ? <p className="py-8 text-center text-sm text-red-300">Unable to load reactions.</p> : <><div className="flex gap-1 overflow-x-auto border-b border-atseen-line pb-2"><button className={`shrink-0 rounded-full px-3 py-1.5 text-xs font-bold ${reactionFilter === "all" ? "bg-atseen-blue text-atseen-bg" : "text-atseen-muted hover:bg-white/5"}`} onClick={() => setReactionFilter("all")} type="button">All · {reactionsQuery.data?.total || 0}</button>{Object.entries(reactionsQuery.data?.counts || {}).map(([type, count]) => <button aria-label={`${reactions[type]?.label} reactions`} className={`flex shrink-0 items-center gap-1 rounded-full px-3 py-1.5 text-xs font-bold ${reactionFilter === type ? "bg-white/10 text-white" : "text-atseen-muted hover:bg-white/5"}`} key={type} onClick={() => setReactionFilter(type)} title={reactions[type]?.label} type="button"><span className="text-base">{reactions[type]?.emoji}</span>{count}</button>)}</div><div className="max-h-[420px] overflow-y-auto py-1">{(reactionsQuery.data?.reactions || []).filter((entry) => reactionFilter === "all" || entry.reaction === reactionFilter).map((entry) => <Link className="flex items-center gap-3 rounded-xl px-2 py-3 transition hover:bg-white/[0.04]" key={entry.id} onClick={() => setReactionsOpen(false)} to={`/profile/${entry.user.username}`}><div className="relative"><FanAvatar name={entry.user.name} size="h-10 w-10" src={entry.user.avatar} /><span className="absolute -bottom-1 -right-1 grid h-5 w-5 place-items-center rounded-full border-2 border-atseen-surface bg-atseen-bg text-[12px]">{reactions[entry.reaction]?.emoji}</span></div><div className="min-w-0"><p className="flex items-center gap-1 truncate text-sm font-bold text-white">{entry.user.name}{entry.user.verified ? <VerifiedBadge /> : null}</p><p className="truncate text-[11px] text-atseen-muted">@{entry.user.username}</p></div><span className={`ml-auto text-xs font-bold ${reactions[entry.reaction]?.color}`}>{reactions[entry.reaction]?.label}</span></Link>)}</div></>}
    </FanModal>
    <FanModal isOpen={shareOpen} onClose={() => { setShareOpen(false); setShareCaption(""); }} title="Share to your profile"><p className="text-sm text-atseen-muted">Add your own note before sharing this Wall post.</p><textarea className="mt-4 min-h-28 w-full resize-y rounded-xl border border-atseen-line bg-atseen-bg p-3 text-sm text-white outline-none focus:border-atseen-blue" maxLength={500} onChange={(event) => setShareCaption(event.target.value)} placeholder="Add a caption (optional)…" value={shareCaption} /><div className="mt-4 overflow-hidden rounded-2xl border border-atseen-line bg-atseen-bg"><div className="flex items-center gap-3 p-3"><FanAvatar name={post.creator.name} size="h-9 w-9" src={post.creator.avatar} /><div className="min-w-0"><p className="flex items-center gap-1 truncate text-xs font-bold">{post.creator.name}{post.creator.verified ? <VerifiedBadge /> : null}</p><p className="text-[10px] text-atseen-muted">@{post.creator.username} · Original Wall post</p></div></div><div className="border-t border-atseen-line p-3"><p className="line-clamp-4 whitespace-pre-wrap text-sm leading-6 text-white/90">{post.text}</p>{post.media?.[0]?.url ? <img alt="Wall post preview" className="mt-3 max-h-52 w-full rounded-xl object-cover" src={post.media[0].url} /> : null}</div></div><p className="mt-2 text-[10px] text-atseen-dim">Preview of how the shared post will appear on your profile.</p><div className="mt-4 flex justify-end gap-2"><button className="rounded-xl border border-atseen-line px-4 py-2 text-sm font-bold" onClick={() => { setShareOpen(false); setShareCaption(""); }} type="button">Cancel</button><button className="rounded-xl bg-atseen-blue px-4 py-2 text-sm font-bold text-atseen-bg" disabled={share.isPending} onClick={() => share.mutate()} type="button">{share.isPending ? "Sharing…" : "Share"}</button></div></FanModal>
    <FanModal isOpen={commentsOpen} onClose={() => setCommentsOpen(false)} title={`Comments · ${post.commentCount}`}><p className="border-b border-atseen-line pb-3 text-sm">{post.text}</p><div className="max-h-80 overflow-y-auto">{commentsQuery.isLoading ? <p className="py-4 text-sm text-atseen-muted">Loading comments…</p> : commentsQuery.data?.map((entry) => <div className="flex gap-3 border-b border-atseen-line py-3" key={entry.id}><FanAvatar name={entry.author.name} size="h-8 w-8" src={entry.author.avatar} /><div><Link className="text-xs font-bold" to={`/profile/${entry.author.username}`}>{entry.author.name}</Link><p className="mt-1 whitespace-pre-wrap text-sm">{entry.text}</p></div></div>)}</div><form className="mt-4 flex gap-2" onSubmit={(event) => { event.preventDefault(); if (text.trim()) comment.mutate(); }}><input className="min-w-0 flex-1 rounded-xl border border-atseen-line bg-atseen-bg p-3" maxLength={500} onChange={(event) => setText(event.target.value)} placeholder="Say something real…" value={text} /><button className="rounded-xl bg-atseen-blue px-4 font-bold text-atseen-bg" disabled={!text.trim() || comment.isPending}>Post</button></form>{error ? <p className="mt-3 text-xs text-red-300">{error}</p> : null}</FanModal>
  </>;
}
