import { useEffect, useState } from "react"; import { FiX } from "react-icons/fi";
const changeReasons = ["TITLE_OR_DESCRIPTION_ISSUE", "MEDIA_UNCLEAR_OR_CORRUPTED", "WRONG_CONTENT_TYPE", "PRIMARY_MEDIA_REQUIRED", "CATEGORY_OR_TAGS_INCORRECT", "ACCESS_LEVEL_INCORRECT", "PPV_PRICE_INVALID", "POLICY_CONCERN", "ADDITIONAL_INFORMATION_REQUIRED", "OTHER"];
const rejectionReasons = ["PROHIBITED_CONTENT", "ILLEGAL_CONTENT", "COPYRIGHT_CONCERN", "HARASSMENT_OR_ABUSE", "EXPLICIT_CONTENT_POLICY", "MISLEADING_CONTENT", "INVALID_MEDIA", "REPEATED_POLICY_VIOLATION", "OTHER"];
export default function ContentDecisionModal({ mode, isOpen, checklistComplete, submitting, onClose, onSubmit }) { const [confirmed, setConfirmed] = useState(false); const [reasonCodes, setReasonCodes] = useState([]); const [rejectionReason, setRejectionReason] = useState(""); const [creatorVisibleMessage, setCreatorVisibleMessage] = useState(""); const [internalNote, setInternalNote] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (isOpen) { setConfirmed(false); setReasonCodes([]); setRejectionReason(""); setCreatorVisibleMessage(""); setInternalNote(""); setError(""); } }, [isOpen, mode]); if (!isOpen) return null;
  const toggle = (reason) => setReasonCodes((current) => current.includes(reason) ? current.filter((item) => item !== reason) : [...current, reason]);
  const submit = async () => { if (mode === "approve" && (!checklistComplete || !confirmed)) return setError("Complete the checklist and explicitly confirm the manual review."); if (mode === "changes" && (!reasonCodes.length || !creatorVisibleMessage.trim())) return setError("Select at least one reason and enter a creator-visible message."); if (mode === "reject" && (!rejectionReason || !creatorVisibleMessage.trim())) return setError("Select a rejection reason and enter a creator-visible message."); setError(""); await onSubmit({ manualReviewConfirmed: mode === "approve" ? true : undefined, reasonCodes, rejectionReason, creatorVisibleMessage: creatorVisibleMessage.trim(), internalNote: internalNote.trim() }); };
  const title = mode === "approve" ? "Approve content" : mode === "changes" ? "Request content changes" : "Reject content";
  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/60 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{title}</h2><button aria-label="Close" disabled={submitting} onClick={onClose} type="button"><FiX /></button></div>{mode === "approve" ? <label className="mt-6 flex gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm"><input checked={confirmed} className="mt-1" onChange={(event) => setConfirmed(event.target.checked)} type="checkbox" /><span>I confirm that I manually reviewed the content and completed every checklist item.</span></label> : null}{mode === "changes" ? <fieldset className="mt-6"><legend className="text-sm font-bold">Reason codes</legend><div className="mt-3 grid gap-2 sm:grid-cols-2">{changeReasons.map((reason) => <label className="flex gap-2 rounded-lg border border-slate-200 p-3 text-xs" key={reason}><input checked={reasonCodes.includes(reason)} onChange={() => toggle(reason)} type="checkbox" />{reason.replaceAll("_", " ")}</label>)}</div></fieldset> : null}{mode === "reject" ? <label className="mt-6 block text-sm font-bold">Rejection reason<select className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal" onChange={(event) => setRejectionReason(event.target.value)} value={rejectionReason}><option value="">Select reason</option>{rejectionReasons.map((reason) => <option key={reason} value={reason}>{reason.replaceAll("_", " ")}</option>)}</select></label> : null}{mode !== "approve" ? <label className="mt-5 block text-sm font-bold">Creator-visible message<textarea className="mt-2 min-h-28 w-full rounded-xl border border-slate-200 p-3 font-normal" maxLength="2000" onChange={(event) => setCreatorVisibleMessage(event.target.value)} value={creatorVisibleMessage} /></label> : null}<label className="mt-5 block text-sm font-bold">Internal admin note <span className="font-normal text-slate-400">(optional)</span><textarea className="mt-2 min-h-24 w-full rounded-xl border border-slate-200 p-3 font-normal" maxLength="2000" onChange={(event) => setInternalNote(event.target.value)} value={internalNote} /></label>{error ? <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}<div className="mt-6 flex justify-end gap-3"><button className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold" disabled={submitting} onClick={onClose} type="button">Cancel</button><button className={`rounded-xl px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50 ${mode === "approve" ? "bg-emerald-600" : mode === "changes" ? "bg-orange-500" : "bg-red-600"}`} disabled={submitting} onClick={submit} type="button">{submitting ? "Saving..." : title}</button></div></div></div>;
}
