import { useEffect, useMemo, useRef } from "react";
import { FiCheck, FiRefreshCw, FiStar, FiTrash2, FiUpload } from "react-icons/fi";
import { mediaAccept } from "../../utils/content";

export default function MediaUploader({ contentType, files, onFilesChange, media, onMediaChange, uploads, onUpload, disabled }) {
  const inputRef = useRef(null); const previews = useMemo(() => files.map((file) => ({ file, url: URL.createObjectURL(file) })), [files]);
  useEffect(() => () => previews.forEach((item) => URL.revokeObjectURL(item.url)), [previews]);
  if (contentType === "TEXT") return <div className="rounded-2xl border border-white/10 bg-white/5 p-5 text-sm text-brand-mist/65">Text posts do not require media.</div>;
  const max = contentType === "IMAGE" ? 10 : 1;
  const select = (event) => { const selected = Array.from(event.target.files || []); event.target.value = ""; onFilesChange(contentType === "IMAGE" ? [...files, ...selected].slice(0, max) : selected.slice(0, 1)); };
  const togglePrimary = (assetId) => onMediaChange(media.map((item) => ({ ...item, isPrimary: item.assetId === assetId })));
  return <div>
    <input accept={mediaAccept[contentType]} className="hidden" multiple={contentType === "IMAGE"} onChange={select} ref={inputRef} type="file" />
    <button className="flex min-h-36 w-full flex-col items-center justify-center rounded-2xl border border-dashed border-white/20 text-brand-mist/65 hover:border-brand-primary" disabled={disabled || media.length + files.length >= max} onClick={() => inputRef.current?.click()} type="button"><FiUpload className="text-3xl text-brand-secondary" /><span className="mt-2 font-semibold">Select {contentType.toLowerCase()} file{contentType === "IMAGE" ? "s" : ""}</span><span className="mt-1 text-xs">{media.length + files.length}/{max}</span></button>
    {previews.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{previews.map(({ file, url }, index) => { const progress = uploads[file.name]; return <div className="rounded-2xl border border-white/10 bg-white/5 p-3" key={`${file.name}-${file.lastModified}`}><div className="flex gap-3">{file.type.startsWith("image/") ? <img alt="Local preview" className="h-16 w-16 rounded-xl object-cover" src={url} /> : <div className="grid h-16 w-16 place-items-center rounded-xl bg-white/10"><FiUpload /></div>}<div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{file.name}</p><p className="mt-1 text-xs text-brand-mist/45">{(file.size / 1024 / 1024).toFixed(1)} MB</p>{progress !== undefined ? <div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-brand-primary" style={{ width: `${progress}%` }} /></div> : null}</div><button aria-label="Remove selected file" disabled={disabled} onClick={() => onFilesChange(files.filter((_, itemIndex) => itemIndex !== index))} type="button"><FiTrash2 /></button></div></div>; })}</div> : null}
    {media.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{media.map((item) => <div className="overflow-hidden rounded-2xl border border-emerald-400/20 bg-emerald-500/5" key={item.assetId}>{item.secureUrl ? <div className="grid min-h-40 place-items-center bg-black/20">{item.mediaType === "IMAGE" ? <img alt="Uploaded content preview" className="max-h-72 w-full object-contain" src={item.secureUrl} /> : item.mediaType === "VIDEO" ? <video className="max-h-72 w-full" controls src={item.secureUrl} /> : <audio className="m-6 w-[calc(100%-3rem)]" controls src={item.secureUrl} />}</div> : null}<div className="flex items-center gap-3 p-3"><FiCheck className="text-emerald-300" /><span className="min-w-0 flex-1 truncate text-sm">{item.assetId.split("/").at(-1)}</span>{contentType === "IMAGE" ? <button className={item.isPrimary ? "text-brand-primary" : "text-brand-mist/40"} onClick={() => togglePrimary(item.assetId)} title="Set primary" type="button"><FiStar /></button> : null}<button aria-label="Remove uploaded media" disabled={disabled} onClick={() => onMediaChange(media.filter((entry) => entry.assetId !== item.assetId))} type="button"><FiTrash2 /></button></div></div>)}</div> : null}
    {files.length ? <button className="mt-4 inline-flex items-center gap-2 rounded-full bg-brand-primary px-5 py-3 text-sm font-semibold disabled:opacity-50" disabled={disabled} onClick={onUpload} type="button">{disabled ? <FiRefreshCw className="animate-spin" /> : <FiUpload />} Upload and attach</button> : null}
  </div>;
}
