import { useCallback, useEffect, useState } from "react"; import { Link } from "react-router-dom"; import { FiArchive, FiEdit3, FiEye, FiPlus, FiSend } from "react-icons/fi";
import Button from "../../components/common/Button"; import CreatorContentCard from "../../components/content/CreatorContentCard"; import { contentService } from "../../services/contentService"; import { ACCESS_LEVELS, CONTENT_STATUSES, CONTENT_TYPES, contentError, formatContentLabel } from "../../utils/content";
export default function ContentManager() {
  const [items, setItems] = useState([]); const [pagination, setPagination] = useState({ page: 1, pages: 1 }); const [filters, setFilters] = useState({ status: "", contentType: "", accessLevel: "", search: "" }); const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const load = useCallback(async (page = 1) => { setLoading(true); setError(""); try { const response = await contentService.listMyContent({ page, limit: 12, status: filters.status || undefined, contentType: filters.contentType || undefined, accessLevel: filters.accessLevel || undefined, search: filters.search.trim() || undefined }); setItems(response.data.data.items || []); setPagination(response.data.data.pagination || { page, pages: 1 }); } catch (requestError) { setError(contentError(requestError, "Unable to load content")); } finally { setLoading(false); } }, [filters.status, filters.contentType, filters.accessLevel, filters.search]);
  useEffect(() => { load(1); }, [load]);
  const act = async (item, action) => { setBusyId(item.id); setError(""); try { if (action === "archive") await contentService.archiveContent(item.id); else if (item.status === "CHANGES_REQUESTED") await contentService.resubmitForReview(item.id); else await contentService.submitForReview(item.id); setSuccess(action === "archive" ? "Content archived" : "Content submitted for review"); await load(pagination.page); } catch (requestError) { setError(contentError(requestError)); if (requestError.response?.status === 409) await load(pagination.page); } finally { setBusyId(""); } };
  const actions = (item) => { const disabled = busyId === item.id; const list = [<Link className="inline-flex items-center gap-1 rounded-full border border-white/10 px-3 py-2 text-xs" key="preview" to={`/creator/content/${item.id}`}><FiEye /> Preview</Link>]; if (["DRAFT", "CHANGES_REQUESTED"].includes(item.status)) list.push(<Link className="inline-flex items-center gap-1 rounded-full border border-white/10 px-3 py-2 text-xs" key="edit" to={`/creator/content/${item.id}/edit`}><FiEdit3 /> Edit</Link>, <button className="inline-flex items-center gap-1 rounded-full bg-brand-primary px-3 py-2 text-xs font-bold" disabled={disabled} key="submit" onClick={() => act(item, "submit")} type="button"><FiSend /> {item.status === "CHANGES_REQUESTED" ? "Resubmit" : "Submit"}</button>); if (["DRAFT", "CHANGES_REQUESTED", "REJECTED", "PUBLISHED"].includes(item.status)) list.push(<button className="inline-flex items-center gap-1 rounded-full border border-white/10 px-3 py-2 text-xs" disabled={disabled} key="archive" onClick={() => act(item, "archive")} type="button"><FiArchive /> Archive</button>); return list; };
  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-secondary">Creator Studio</p><h1 className="mt-2 text-3xl font-black">Content manager</h1><p className="mt-2 text-sm text-brand-mist/55">Manage drafts, review feedback, and published content.</p></div><Link to="/creator/content/new"><Button className="gap-2"><FiPlus /> Create content</Button></Link></div>
    {error ? <p className="mt-5 rounded-2xl border border-red-400/25 bg-red-500/10 p-4 text-sm text-red-200">{error}</p> : null}{success ? <p className="mt-5 rounded-2xl border border-emerald-400/25 bg-emerald-500/10 p-4 text-sm text-emerald-200">{success}</p> : null}
    <div className="mt-6 grid gap-3 rounded-3xl border border-white/10 bg-white/5 p-4 md:grid-cols-4"><input className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm" onChange={(event) => setFilters((current) => ({ ...current, search: event.target.value }))} placeholder="Search title" value={filters.search} />{[["status", CONTENT_STATUSES], ["contentType", CONTENT_TYPES], ["accessLevel", ACCESS_LEVELS]].map(([field, options]) => <select className="rounded-xl border border-white/10 bg-brand-dark px-3 py-2 text-sm" key={field} onChange={(event) => setFilters((current) => ({ ...current, [field]: event.target.value }))} value={filters[field]}><option value="">All {formatContentLabel(field)}</option>{options.map((option) => <option key={option} value={option}>{formatContentLabel(option)}</option>)}</select>)}</div>
    {loading ? <p className="mt-8 text-sm text-brand-mist/55">Loading content...</p> : items.length ? <div className="mt-6 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{items.map((item) => <CreatorContentCard actions={actions(item)} item={item} key={item.id} />)}</div> : <div className="mt-6 rounded-3xl border border-dashed border-white/15 p-12 text-center"><p className="font-bold">No content matches this view.</p><Link className="mt-4 inline-block text-brand-secondary" to="/creator/content/new">Create your first draft</Link></div>}
    {pagination.pages > 1 ? <div className="mt-7 flex justify-center gap-3"><Button disabled={pagination.page <= 1} onClick={() => load(pagination.page - 1)} variant="ghost">Previous</Button><span className="self-center text-sm text-brand-mist/55">{pagination.page} / {pagination.pages}</span><Button disabled={pagination.page >= pagination.pages} onClick={() => load(pagination.page + 1)} variant="ghost">Next</Button></div> : null}
  </div>;
}
