import { useEffect, useState } from "react"; import { Link, useLocation, useParams } from "react-router-dom"; import { FiArchive, FiArrowLeft, FiEdit3, FiFileText, FiLock, FiSend } from "react-icons/fi";
import Button from "../../components/common/Button"; import ContentStatusBadge from "../../components/content/ContentStatusBadge"; import ContentReviewSummary from "../../components/content/ContentReviewSummary"; import ModerationFeedbackPanel from "../../components/content/ModerationFeedbackPanel"; import { contentService } from "../../services/contentService"; import { contentError, formatContentLabel } from "../../utils/content";
const date = (value) => value ? new Date(value).toLocaleString() : "—";
export default function ContentDetailPage() { const { id } = useParams(); const location = useLocation(); const [item, setItem] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(location.state?.success || "");
  const load = () => contentService.getMyContent(id).then((response) => setItem(response.data.data.content)).catch((requestError) => setError(contentError(requestError, "Unable to load content"))).finally(() => setLoading(false));
  useEffect(() => { let active = true; setLoading(true); contentService.getMyContent(id).then((response) => { if (active) setItem(response.data.data.content); }).catch((requestError) => { if (active) setError(contentError(requestError, "Unable to load content")); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [id]);
  const act = async (action) => { setBusy(true); setError(""); try { if (action === "archive") await contentService.archiveContent(id); else if (item.status === "CHANGES_REQUESTED") await contentService.resubmitForReview(id); else await contentService.submitForReview(id); setSuccess(action === "archive" ? "Content archived" : "Content submitted for review"); await load(); } catch (requestError) { setError(contentError(requestError)); if (requestError.response?.status === 409) await load(); } finally { setBusy(false); } };
  if (loading) return <p className="text-sm text-brand-mist/55">Loading content...</p>; if (!item) return <p className="rounded-2xl border border-red-400/20 p-4 text-red-200">{error || "Content not found"}</p>;
  return <div className="mx-auto max-w-5xl"><Link className="inline-flex items-center gap-2 text-sm text-brand-mist/60" to="/creator/content"><FiArrowLeft /> Content manager</Link><div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black">{item.title}</h1><ContentStatusBadge status={item.status} /></div><p className="mt-2 text-sm text-brand-mist/50">{formatContentLabel(item.contentType)} · {formatContentLabel(item.accessLevel)}</p></div><div className="flex flex-wrap gap-2">{["DRAFT", "CHANGES_REQUESTED"].includes(item.status) ? <Link to={`/creator/content/${item.id}/edit`}><Button className="gap-2" variant="secondary"><FiEdit3 /> Edit</Button></Link> : null}{["DRAFT", "CHANGES_REQUESTED"].includes(item.status) ? <Button className="gap-2" disabled={busy} onClick={() => act("submit")}><FiSend /> {item.status === "CHANGES_REQUESTED" ? "Resubmit" : "Submit"}</Button> : null}{["DRAFT", "CHANGES_REQUESTED", "REJECTED", "PUBLISHED"].includes(item.status) ? <Button className="gap-2" disabled={busy} onClick={() => act("archive")} variant="ghost"><FiArchive /> Archive</Button> : null}</div></div>
    {item.status === "PENDING_REVIEW" ? <div className="mt-5 flex gap-3 rounded-2xl border border-amber-400/20 bg-amber-500/10 p-4 text-sm text-amber-100"><FiLock className="mt-0.5" /> Editing is locked while an admin manually reviews this content.</div> : null}<ModerationFeedbackPanel feedback={item.creatorFeedback} status={item.status} />{error ? <p className="mt-5 rounded-2xl border border-red-400/25 bg-red-500/10 p-4 text-sm text-red-200">{error}</p> : null}{success ? <p className="mt-5 rounded-2xl border border-emerald-400/25 bg-emerald-500/10 p-4 text-sm text-emerald-200">{success}</p> : null}
    <div className="mt-6"><ContentReviewSummary content={item} /></div><section className="mt-6 rounded-3xl border border-white/10 bg-white/5 p-5"><h2 className="text-xl font-bold">Media preview</h2>{item.media?.length ? <div className="mt-4 grid gap-4 sm:grid-cols-2">{item.media.map((media) => <div className="overflow-hidden rounded-2xl border border-white/10" key={media.assetId}>{media.mediaType === "IMAGE" ? <img alt="Content preview" className="max-h-96 w-full object-contain" src={media.secureUrl} /> : media.mediaType === "VIDEO" ? <video className="w-full" controls src={media.secureUrl} /> : <audio className="m-4 w-[calc(100%-2rem)]" controls src={media.secureUrl} />}</div>)}</div> : <div className="mt-4 flex items-center gap-3 text-sm text-brand-mist/55"><FiFileText /> No media attached</div>}</section>
    <section className="mt-6 rounded-3xl border border-white/10 bg-white/5 p-5"><h2 className="font-bold">Dates</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-brand-mist/45">Created</dt><dd>{date(item.createdAt)}</dd></div><div><dt className="text-brand-mist/45">Submitted</dt><dd>{date(item.submittedAt)}</dd></div><div><dt className="text-brand-mist/45">Reviewed</dt><dd>{date(item.reviewedAt)}</dd></div><div><dt className="text-brand-mist/45">Published</dt><dd>{date(item.publishedAt)}</dd></div></dl></section>
  </div>; }
