import { useEffect, useMemo, useState } from "react";
import { Link, Navigate, useNavigate, useParams } from "react-router-dom";
import { FiArrowLeft, FiArrowRight, FiCheck, FiSave } from "react-icons/fi";
import Button from "../../components/common/Button"; import Loader from "../../components/common/Loader"; import Modal from "../../components/common/Modal";
import ContentTypeSelector from "../../components/content/ContentTypeSelector"; import AccessLevelSelector from "../../components/content/AccessLevelSelector"; import MediaUploader from "../../components/content/MediaUploader"; import ContentReviewSummary from "../../components/content/ContentReviewSummary"; import ModerationFeedbackPanel from "../../components/content/ModerationFeedbackPanel";
import { contentService } from "../../services/contentService"; import { contentError, EDITABLE_STATUSES } from "../../utils/content";

const steps = ["Type", "Details", "Media", "Access", "Review"];
const initial = { title: "", description: "", body: "", category: "", tags: [], contentType: "IMAGE", accessLevel: "PUBLIC", coinPrice: null, media: [] };
const editablePayload = (form) => ({ title: form.title.trim(), description: form.description.trim(), body: form.body, category: form.category.trim(), tags: form.tags, contentType: form.contentType, accessLevel: form.accessLevel, coinPrice: form.accessLevel === "PAY_PER_VIEW" ? Number(form.coinPrice) : null, media: (form.media || []).map((item) => ({ assetId: item.assetId, isPrimary: Boolean(item.isPrimary) })) });

export default function ContentComposerPage() {
  const { id } = useParams(); const navigate = useNavigate(); const editing = Boolean(id);
  const [form, setForm] = useState(initial); const [draft, setDraft] = useState(null); const [step, setStep] = useState(0); const [tagInput, setTagInput] = useState("");
  const [files, setFiles] = useState([]); const [uploads, setUploads] = useState({}); const [loading, setLoading] = useState(editing); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [confirmOpen, setConfirmOpen] = useState(false);
  useEffect(() => { if (!id) return; contentService.getMyContent(id).then((response) => { const content = response.data.data.content; setDraft(content); setForm({ ...initial, ...content, coinPrice: content.coinPrice ?? "", media: content.media || [] }); }).catch((requestError) => setError(contentError(requestError, "Unable to load content"))).finally(() => setLoading(false)); }, [id]);
  const editable = !draft || EDITABLE_STATUSES.includes(draft.status); const canContinueDetails = form.title.trim() && form.category.trim();
  const summary = useMemo(() => ({ ...form, media: form.media || [] }), [form]);
  if (!loading && draft && !editable) return <Navigate replace to={`/creator/content/${draft.id}`} />;
  const change = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const addTag = () => { const tag = tagInput.trim().toLowerCase(); if (tag && !form.tags.includes(tag) && form.tags.length < 15 && tag.length <= 40) change("tags", [...form.tags, tag]); setTagInput(""); };
  const refresh = async (contentId = draft?.id) => { const response = await contentService.getMyContent(contentId); const content = response.data.data.content; setDraft(content); setForm((current) => ({ ...current, ...content, coinPrice: content.coinPrice ?? "", media: content.media || [] })); return content; };
  const save = async ({ quiet = false } = {}) => {
    if (busy) return draft; setBusy(true); setError(""); setSuccess("");
    try { let content; if (draft) { await contentService.updateDraft(draft.id, { ...editablePayload(form), statusVersion: draft.statusVersion }); content = await refresh(draft.id); } else { const response = await contentService.createDraft(editablePayload(form)); content = response.data.data.content; setDraft(content); setForm((current) => ({ ...current, ...content, media: content.media || [] })); }
      if (!quiet) setSuccess("Draft saved"); return content;
    } catch (requestError) { setError(contentError(requestError, "Unable to save draft")); if (requestError.response?.status === 409 && draft?.id) await refresh().catch(() => {}); return null; } finally { setBusy(false); }
  };
  const next = async () => { if (step === 1 && !draft) { const created = await save({ quiet: true }); if (!created) return; } setStep((current) => Math.min(4, current + 1)); };
  const uploadFiles = async () => {
    let currentDraft = draft; if (!currentDraft) currentDraft = await save({ quiet: true }); if (!currentDraft || !files.length) return;
    setBusy(true); setError("");
    try { const contractResponse = await contentService.requestUploadContract(currentDraft.id); const uploadContract = contractResponse.data.data; const attached = [...(form.media || [])];
      for (const file of files) { const asset = await contentService.uploadDraftMedia(file, uploadContract, (progress) => setUploads((current) => ({ ...current, [file.name]: progress }))); attached.push({ assetId: asset.public_id, isPrimary: form.contentType === "IMAGE" ? !attached.some((entry) => entry.isPrimary) : false }); }
      await contentService.updateDraft(currentDraft.id, { media: attached, statusVersion: currentDraft.statusVersion }); await refresh(currentDraft.id); setFiles([]); setUploads({}); setSuccess("Media uploaded and verified");
    } catch (requestError) { setError(contentError(requestError, "Media upload or verification failed")); if (requestError.response?.status === 409) await refresh().catch(() => {}); } finally { setBusy(false); }
  };
  const submit = async () => { setError(""); try { const saved = await save({ quiet: true }); if (!saved) return; setBusy(true); const method = saved.status === "CHANGES_REQUESTED" ? "resubmitForReview" : "submitForReview"; const response = await contentService[method](saved.id); navigate(`/creator/content/${response.data.data.content.id}`, { replace: true, state: { success: "Content submitted for manual review" } }); } catch (requestError) { setError(contentError(requestError, "Unable to submit content")); if (requestError.response?.status === 409) await refresh().catch(() => {}); } finally { setBusy(false); setConfirmOpen(false); } };
  if (loading) return <Loader label="Loading content..." />;
  return <div className="mx-auto max-w-5xl"><Link className="inline-flex items-center gap-2 text-sm text-brand-mist/60" to="/creator/content"><FiArrowLeft /> Content manager</Link>
    <div className="mt-5"><p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-secondary">Creator composer</p><h1 className="mt-2 text-3xl font-black">{editing ? "Edit content" : "Create content"}</h1>{draft ? <p className="mt-2 text-sm text-brand-mist/50">Draft ID: {draft.id}</p> : null}</div>
    <ModerationFeedbackPanel feedback={draft?.creatorFeedback} status={draft?.status} />
    {error ? <div className="mt-5 rounded-2xl border border-red-400/25 bg-red-500/10 p-4 text-sm text-red-200">{error}</div> : null}{success ? <div className="mt-5 flex items-center gap-2 rounded-2xl border border-emerald-400/25 bg-emerald-500/10 p-4 text-sm text-emerald-200"><FiCheck /> {success}</div> : null}
    <div className="mt-6 flex gap-2 overflow-x-auto">{steps.map((label, index) => <button className={`min-w-24 rounded-full px-4 py-2 text-xs font-bold ${step === index ? "bg-brand-primary text-white" : "bg-white/5 text-brand-mist/50"}`} key={label} onClick={() => setStep(index)} type="button">{index + 1}. {label}</button>)}</div>
    <section className="mt-5 rounded-3xl border border-white/10 bg-brand-dark/60 p-5 sm:p-7">
      {step === 0 ? <><h2 className="text-xl font-bold">Select content type</h2><div className="mt-5"><ContentTypeSelector disabled={Boolean(draft?.media?.length)} onChange={(value) => change("contentType", value)} value={form.contentType} /></div></> : null}
      {step === 1 ? <><h2 className="text-xl font-bold">Content details</h2><div className="mt-5 grid gap-5"><label>Title <span className="float-right text-xs text-brand-mist/40">{form.title.length}/120</span><input className="mt-2 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3" maxLength="120" onChange={(event) => change("title", event.target.value)} value={form.title} /></label><label>Description <span className="float-right text-xs text-brand-mist/40">{form.description.length}/2000</span><textarea className="mt-2 min-h-28 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3" maxLength="2000" onChange={(event) => change("description", event.target.value)} value={form.description} /></label>{form.contentType === "TEXT" ? <label>Body <span className="float-right text-xs text-brand-mist/40">{form.body.length}/10000</span><textarea className="mt-2 min-h-64 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3" maxLength="10000" onChange={(event) => change("body", event.target.value)} value={form.body} /></label> : null}<label>Category<input className="mt-2 w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3" maxLength="40" onChange={(event) => change("category", event.target.value)} value={form.category} /></label><div><label htmlFor="tags">Tags ({form.tags.length}/15)</label><div className="mt-2 flex gap-2"><input className="min-w-0 flex-1 rounded-2xl border border-white/10 bg-white/5 px-4 py-3" id="tags" maxLength="40" onChange={(event) => setTagInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === ",") { event.preventDefault(); addTag(); } }} value={tagInput} /><Button onClick={addTag} type="button" variant="secondary">Add</Button></div><div className="mt-2 flex flex-wrap gap-2">{form.tags.map((tag) => <button className="rounded-full bg-white/10 px-3 py-1 text-xs" key={tag} onClick={() => change("tags", form.tags.filter((item) => item !== tag))} type="button">{tag} ×</button>)}</div></div></div></> : null}
      {step === 2 ? <><h2 className="text-xl font-bold">Upload media</h2><p className="mt-2 text-sm text-brand-mist/55">Uploads are signed for this draft and verified by the backend before attachment.</p><div className="mt-5"><MediaUploader contentType={form.contentType} disabled={busy} files={files} media={form.media || []} onFilesChange={setFiles} onMediaChange={(media) => change("media", media)} onUpload={uploadFiles} uploads={uploads} /></div></> : null}
      {step === 3 ? <><h2 className="text-xl font-bold">Select access</h2><div className="mt-5"><AccessLevelSelector coinPrice={form.coinPrice ?? ""} onChange={(value) => { change("accessLevel", value); if (value !== "PAY_PER_VIEW") change("coinPrice", null); }} onCoinPriceChange={(value) => change("coinPrice", value)} value={form.accessLevel} /></div></> : null}
      {step === 4 ? <><h2 className="text-xl font-bold">Review and submit</h2><p className="mt-2 text-sm text-brand-mist/55">Submission sends this content to manual admin review. It will not publish immediately.</p><div className="mt-5"><ContentReviewSummary content={summary} /></div></> : null}
      <div className="mt-7 flex flex-wrap justify-between gap-3"><Button disabled={busy || step === 0} onClick={() => setStep((current) => Math.max(0, current - 1))} type="button" variant="ghost"><FiArrowLeft /> Back</Button><div className="flex flex-wrap gap-3"><Button disabled={busy || !canContinueDetails} onClick={() => save()} type="button" variant="secondary"><FiSave /> Save draft</Button>{step < 4 ? <Button disabled={busy || (step === 1 && !canContinueDetails)} onClick={next} type="button">Continue <FiArrowRight /></Button> : <Button disabled={busy} onClick={() => setConfirmOpen(true)} type="button">{draft?.status === "CHANGES_REQUESTED" ? "Resubmit for review" : "Submit for review"}</Button>}</div></div>
    </section>
    <Modal isOpen={confirmOpen} onClose={() => !busy && setConfirmOpen(false)} title="Submit for manual review?"><p className="text-sm text-brand-mist/65">You will not be able to edit this post while it is pending review.</p><div className="mt-6 flex justify-end gap-3"><Button disabled={busy} onClick={() => setConfirmOpen(false)} variant="ghost">Cancel</Button><Button disabled={busy} onClick={submit}>{busy ? "Submitting..." : "Confirm submission"}</Button></div></Modal>
  </div>;
}
