import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { FiArrowRight, FiCheckCircle, FiClock, FiEdit3, FiFileText, FiPlus } from "react-icons/fi";
import Button from "../../components/common/Button";
import ContentStatusBadge from "../../components/content/ContentStatusBadge";
import { useAuth } from "../../hooks/useAuth";
import { contentService } from "../../services/contentService";
import { contentError, formatContentLabel } from "../../utils/content";

const statuses = ["DRAFT", "PENDING_REVIEW", "CHANGES_REQUESTED", "PUBLISHED", "REJECTED", "ARCHIVED"];
const statCards = [{ key: "total", label: "All content", icon: FiFileText }, { key: "DRAFT", label: "Drafts", icon: FiEdit3 }, { key: "PENDING_REVIEW", label: "In review", icon: FiClock }, { key: "PUBLISHED", label: "Published", icon: FiCheckCircle }];

export default function CreatorStudio() {
  const { user } = useAuth();
  const [items, setItems] = useState([]); const [total, setTotal] = useState(0); const [counts, setCounts] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { Promise.all([contentService.listMyContent({ limit: 5 }), ...statuses.map((status) => contentService.listMyContent({ limit: 1, status }))]).then(([recent, ...responses]) => { setItems(recent.data.data.items || []); setTotal(recent.data.data.pagination?.total || 0); setCounts(Object.fromEntries(statuses.map((status, index) => [status, responses[index].data.data.pagination?.total || 0]))); }).catch((e) => setError(contentError(e, "Unable to load studio"))).finally(() => setLoading(false)); }, []);
  const values = { ...counts, total };
  return <div className="mx-auto max-w-7xl"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="creator-eyebrow">Creator studio</p><h1 className="creator-page-title">Good to see you, {user?.name?.split(" ")[0] || "Creator"}</h1><p className="creator-muted mt-2">Structured Seens and legacy Content stay separate.</p><div className="mt-3 flex gap-4 text-sm font-bold"><Link className="text-sky-300" to="/studio/seens">Manage Seens</Link><Link className="text-slate-400" to="/creator/content">Legacy Content</Link><span className="text-slate-500">Future Worlds · Coming next phase</span></div></div><Link to="/create"><Button className="gap-2"><FiPlus /> Create</Button></Link></div>
    {error ? <p className="mt-5 rounded-xl border border-red-400/20 bg-red-500/10 p-4 text-sm text-red-200">{error}</p> : null}
    <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{statCards.map(({ key, label, icon: Icon }) => <div className="creator-card p-5" key={key}><div className="flex items-center justify-between"><span className="rounded-xl bg-sky-300/10 p-2.5 text-sky-300"><Icon /></span><span className="text-xs text-slate-500">Live</span></div><p className="mt-5 text-3xl font-black">{loading ? "—" : values[key] || 0}</p><p className="mt-1 text-sm text-slate-400">{label}</p></div>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><section className="creator-card overflow-hidden"><div className="flex items-center justify-between border-b border-white/[0.07] p-5"><div><h2 className="font-bold">Recent content</h2><p className="mt-1 text-xs text-slate-500">Your latest drafts and submissions</p></div><Link className="inline-flex items-center gap-2 text-sm font-semibold text-sky-300" to="/creator/content">View all <FiArrowRight /></Link></div>{!loading && !items.length ? <div className="p-12 text-center"><p className="text-slate-400">Your studio is ready for its first post.</p><Link className="mt-3 inline-block text-sm font-semibold text-sky-300" to="/creator/content/new">Create a draft</Link></div> : <div className="divide-y divide-white/[0.07]">{items.map((item) => <Link className="flex items-center justify-between gap-4 p-5 transition hover:bg-white/[0.025]" key={item.id} to={`/creator/content/${item.id}`}><div className="min-w-0"><p className="truncate font-semibold">{item.title}</p><p className="mt-1 text-xs text-slate-500">{formatContentLabel(item.contentType)} · {new Date(item.createdAt).toLocaleDateString()}</p></div><ContentStatusBadge status={item.status} /></Link>)}</div>}</section>
      <aside className="space-y-5"><div className="creator-card p-5"><p className="creator-eyebrow">Review pipeline</p><div className="mt-4 space-y-3">{statuses.slice(0, 5).map((status) => <div className="flex items-center justify-between text-sm" key={status}><span className="text-slate-400">{formatContentLabel(status)}</span><span className="font-bold">{loading ? "—" : counts[status] || 0}</span></div>)}</div></div><div className="creator-card bg-gradient-to-br from-sky-400/10 to-transparent p-5"><h2 className="font-bold">Build your profile</h2><p className="mt-2 text-sm leading-6 text-slate-400">A complete public profile helps fans understand what you create.</p><Link className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-sky-300" to="/creator/profile">Edit profile <FiArrowRight /></Link></div></aside></div>
  </div>;
}
