import { useState } from "react"; import { Link, useSearchParams } from "react-router-dom"; import { useQueries, useQuery, useQueryClient } from "@tanstack/react-query"; import { FiChevronLeft, FiChevronRight, FiFileText, FiHeadphones, FiImage, FiRefreshCw, FiSearch, FiVideo } from "react-icons/fi";
import Loader from "../../components/common/Loader"; import AdminContentStatusBadge from "../../components/admin/AdminContentStatusBadge"; import { adminContentService } from "../../services/adminContentService";
const statuses = ["PENDING_REVIEW", "CHANGES_REQUESTED", "PUBLISHED", "REJECTED", "ARCHIVED"]; const types = ["IMAGE", "VIDEO", "AUDIO", "TEXT"]; const accesses = ["PUBLIC", "SUBSCRIBER_ONLY", "PAY_PER_VIEW"]; const icons = { IMAGE: FiImage, VIDEO: FiVideo, AUDIO: FiHeadphones, TEXT: FiFileText };
const readError = (error) => error.response?.data?.message || "Unable to load the moderation queue.";
export default function ContentModeration() { const queryClient = useQueryClient(); const [params, setParams] = useSearchParams({ status: "PENDING_REVIEW" }); const [creatorSearch, setCreatorSearch] = useState(params.get("creator") || "");
  const filters = { page: Math.max(1, Number(params.get("page")) || 1), limit: 20, status: params.get("status") || "PENDING_REVIEW", contentType: params.get("contentType") || undefined, accessLevel: params.get("accessLevel") || undefined, category: params.get("category") || undefined, creator: params.get("creator") || undefined, submittedFrom: params.get("submittedFrom") || undefined, sort: params.get("sort") || "newest" };
  const update = (key, value) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); if (key !== "page") next.set("page", "1"); setParams(next); };
  const queue = useQuery({ queryKey: ["admin", "content-moderation", filters], queryFn: () => adminContentService.listModerationContent(filters).then((response) => response.data.data), placeholderData: (previous) => previous });
  const summaries = useQueries({ queries: statuses.map((status) => ({ queryKey: ["admin", "content-moderation-count", status], queryFn: () => adminContentService.listModerationContent({ status, page: 1, limit: 1 }).then((response) => response.data.data.pagination.total) })) });
  const pagination = queue.data?.pagination; const items = queue.data?.items || [];
  return <div className="mx-auto max-w-[1700px]"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-orange-500">Trust and safety</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">Content moderation</h1><p className="mt-1 text-sm text-slate-500">Manually review creator submissions before publication.</p></div><button className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold shadow-sm" onClick={() => queryClient.invalidateQueries({ queryKey: ["admin", "content-moderation"] })} type="button"><FiRefreshCw /> Refresh</button></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{statuses.map((status, index) => <button className="rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm hover:border-orange-300" key={status} onClick={() => update("status", status)} type="button"><p className="text-sm text-slate-500">{status.replaceAll("_", " ")}</p><p className="mt-2 text-3xl font-black">{summaries[index].isLoading ? "…" : summaries[index].data ?? "—"}</p></button>)}</div>
    <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><form className="grid gap-3 border-b border-slate-200 p-4 lg:grid-cols-4 xl:grid-cols-8" onSubmit={(event) => { event.preventDefault(); update("creator", creatorSearch.trim()); }}><label className="relative lg:col-span-2"><FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 text-sm" onChange={(event) => setCreatorSearch(event.target.value)} placeholder="Creator name or username" value={creatorSearch} /></label><select className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" onChange={(event) => update("status", event.target.value)} value={filters.status}><option value="">All statuses</option>{["DRAFT", ...statuses].map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select><select className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" onChange={(event) => update("contentType", event.target.value)} value={filters.contentType || ""}><option value="">All types</option>{types.map((value) => <option key={value}>{value}</option>)}</select><select className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" onChange={(event) => update("accessLevel", event.target.value)} value={filters.accessLevel || ""}><option value="">All access</option>{accesses.map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select><input className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" defaultValue={filters.category || ""} onBlur={(event) => update("category", event.target.value.trim())} placeholder="Category" /><input className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" onChange={(event) => update("submittedFrom", event.target.value)} type="date" value={filters.submittedFrom || ""} /><select className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" onChange={(event) => update("sort", event.target.value)} value={filters.sort}><option value="newest">Newest submitted</option><option value="oldest">Oldest submitted</option><option value="creator">Creator name</option><option value="title">Content title</option></select><button className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white" type="submit">Apply search</button></form>
      {queue.isLoading ? <div className="p-10"><Loader label="Loading moderation queue..." /></div> : queue.isError ? <div className="m-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{readError(queue.error)} <button className="font-bold underline" onClick={() => queue.refetch()} type="button">Retry</button></div> : !items.length ? <div className="grid min-h-64 place-items-center text-center"><div><FiFileText className="mx-auto text-4xl text-slate-300" /><p className="mt-3 font-bold text-slate-600">No content matches these filters</p></div></div> : <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Content</th><th className="p-4">Creator</th><th className="p-4">Type / access</th><th className="p-4">Status</th><th className="p-4">Submitted</th><th className="p-4">Created</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => { const Icon = icons[item.contentType] || FiFileText; const primary = item.media?.find((media) => media.isPrimary); return <tr key={item.id}><td className="p-4"><div className="flex items-center gap-3">{primary?.secureUrl ? <img alt="" className="h-12 w-16 rounded-lg object-cover" src={primary.secureUrl} /> : <span className="grid h-12 w-16 place-items-center rounded-lg bg-slate-100"><Icon /></span>}<div><p className="max-w-56 truncate font-bold">{item.title}</p><p className="mt-1 text-xs text-slate-400">{item.category || "Uncategorized"}</p></div></div></td><td className="p-4"><p className="font-semibold">{item.creator?.name || "Unknown"}</p><p className="text-xs text-slate-500">@{item.creator?.username || "unknown"}</p></td><td className="p-4"><p>{item.contentType}</p><p className="text-xs text-slate-500">{item.accessLevel?.replaceAll("_", " ")}{item.accessLevel === "PAY_PER_VIEW" ? ` · ${item.coinPrice} coins` : ""}</p></td><td className="p-4"><AdminContentStatusBadge status={item.status} /></td><td className="p-4 text-slate-500">{item.submittedAt ? new Date(item.submittedAt).toLocaleDateString() : "—"}</td><td className="p-4 text-slate-500">{new Date(item.createdAt).toLocaleDateString()}</td><td className="p-4"><Link className="rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white" to={`/admin/content-moderation/${item.id}`}>Review</Link></td></tr>; })}</tbody></table></div>}
      {pagination ? <div className="flex items-center justify-between border-t border-slate-200 p-4"><p className="text-xs text-slate-500">Page {pagination.page} of {pagination.pages || 1} · {pagination.total} records</p><div className="flex gap-2"><button className="rounded-lg border border-slate-200 p-2 disabled:opacity-40" disabled={pagination.page <= 1} onClick={() => update("page", pagination.page - 1)} type="button"><FiChevronLeft /></button><button className="rounded-lg border border-slate-200 p-2 disabled:opacity-40" disabled={pagination.page >= pagination.pages} onClick={() => update("page", pagination.page + 1)} type="button"><FiChevronRight /></button></div></div> : null}
    </section>
  </div>;
}
