import { useState } from "react"; import { Link, useParams } from "react-router-dom"; import { useQuery, useQueryClient } from "@tanstack/react-query"; import { FiArrowLeft, FiCheckCircle, FiClock, FiLock, FiUser } from "react-icons/fi";
import Loader from "../../components/common/Loader"; import AdminContentStatusBadge from "../../components/admin/AdminContentStatusBadge"; import AdminContentMediaPreview from "../../components/admin/AdminContentMediaPreview"; import ContentHistoryTimeline from "../../components/admin/ContentHistoryTimeline"; import ContentDecisionModal from "../../components/admin/ContentDecisionModal"; import { adminContentService } from "../../services/adminContentService";
const checklistItems = ["Content title and description are appropriate", "Uploaded media matches the selected content type", "Media is viewable and not corrupted", "Primary image or thumbnail is appropriate", "Category and tags are relevant", "Access level is appropriate", "PPV price is valid where applicable", "Content does not obviously violate platform policy", "Creator information and content appear consistent"];
const date = (value) => value ? new Date(value).toLocaleString() : "—"; const message = (error, fallback) => error.response?.data?.message || fallback;
export default function ContentModerationDetail() { const { id } = useParams(); const queryClient = useQueryClient(); const [checklist, setChecklist] = useState({}); const [modal, setModal] = useState(""); const [submitting, setSubmitting] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const detail = useQuery({ queryKey: ["admin", "content-moderation", id], queryFn: () => adminContentService.getModerationContent(id).then((response) => response.data.data) });
  const history = useQuery({ queryKey: ["admin", "content-moderation", id, "history"], queryFn: () => adminContentService.getModerationHistory(id).then((response) => response.data.data.history) });
  if (detail.isLoading) return <Loader label="Loading moderation detail..." />; if (detail.isError) return <div className="rounded-xl border border-red-200 bg-red-50 p-5 text-red-700">{detail.error.response?.status === 404 ? "Content was not found." : "Unable to load moderation detail."}</div>;
  const content = detail.data.content; const profile = detail.data.creatorProfile; const canDecide = content.status === "PENDING_REVIEW"; const checklistComplete = checklistItems.every((item) => checklist[item]); const legacy = content.legacyMigration?.legacyPublished;
  const refresh = async () => { await Promise.all([detail.refetch(), history.refetch()]); queryClient.invalidateQueries({ queryKey: ["admin", "content-moderation-count"] }); };
  const decide = async (payload) => { setSubmitting(true); setError(""); setNotice(""); try { if (modal === "approve") await adminContentService.approveContent(id, { manualReviewConfirmed: payload.manualReviewConfirmed, internalNote: payload.internalNote }); else if (modal === "changes") await adminContentService.requestContentChanges(id, { reasonCodes: payload.reasonCodes, creatorVisibleMessage: payload.creatorVisibleMessage, internalNote: payload.internalNote }); else await adminContentService.rejectContent(id, { rejectionReason: payload.rejectionReason, creatorVisibleMessage: payload.creatorVisibleMessage, internalNote: payload.internalNote }); setNotice(modal === "approve" ? "Content approved and published." : modal === "changes" ? "Changes requested from the creator." : "Content rejected."); setModal(""); await refresh(); } catch (requestError) { if (requestError.response?.status === 409) { await refresh(); setError("Another reviewer already changed this content. The latest state has been loaded."); } else setError(message(requestError, "Unable to save the moderation decision.")); } finally { setSubmitting(false); } };
  const accessCopy = content.accessLevel === "PUBLIC" ? "This content will be publicly visible after publication." : content.accessLevel === "SUBSCRIBER_ONLY" ? "Locked for normal users until subscription entitlement is implemented." : `Locked until PPV entitlement is implemented. Listed price: ${content.coinPrice} coins.`;
  return <div className="mx-auto max-w-[1700px]"><Link className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-slate-900" to="/admin/content-moderation"><FiArrowLeft /> Moderation queue</Link><div className="mt-5 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black">{content.title}</h1><AdminContentStatusBadge status={content.status} />{legacy ? <span className="rounded-full bg-blue-100 px-2.5 py-1 text-[10px] font-black uppercase text-blue-700">Legacy published</span> : null}</div><p className="mt-2 text-sm text-slate-500">Manual content review · Version {content.statusVersion ?? "—"}</p></div>{canDecide ? <div className="flex flex-wrap gap-2"><button className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40" disabled={!checklistComplete} onClick={() => setModal("approve")} type="button">Approve</button><button className="rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-bold text-white" onClick={() => setModal("changes")} type="button">Request changes</button><button className="rounded-xl bg-red-600 px-4 py-2.5 text-sm font-bold text-white" onClick={() => setModal("reject")} type="button">Reject</button></div> : <div className="inline-flex items-center gap-2 rounded-xl bg-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600"><FiLock /> Read-only state</div>}</div>
    {notice ? <div className="mt-5 flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700"><FiCheckCircle /> {notice}</div> : null}{error ? <div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div> : null}{legacy ? <div className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">This record predates manual content moderation. Legacy migration does not mean it was manually reviewed.</div> : null}
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_420px]"><div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Content summary</h2><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4">{[["Type", content.contentType], ["Access", content.accessLevel?.replaceAll("_", " ")], ["Price", content.accessLevel === "PAY_PER_VIEW" ? `${content.coinPrice} coins` : "—"], ["Category", content.category || "—"], ["Tags", content.tags?.join(", ") || "—"], ["Created", date(content.createdAt)], ["Submitted", date(content.submittedAt)], ["Published", date(content.publishedAt)], ["Archived", date(content.archivedAt)]].map(([label, value]) => <div key={label}><dt className="text-xs font-bold uppercase text-slate-400">{label}</dt><dd className="mt-1 text-slate-700">{value}</dd></div>)}</dl></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Creator summary</h2><div className="mt-5 flex items-start gap-4">{content.creator?.avatar ? <img alt="" className="h-14 w-14 rounded-xl object-cover" src={content.creator.avatar} /> : <span className="grid h-14 w-14 place-items-center rounded-xl bg-slate-100"><FiUser /></span>}<div><p className="font-bold">{content.creator?.name || "Unknown creator"}</p><p className="text-sm text-slate-500">@{content.creator?.username || "unknown"} · {content.creator?.email || "No email"}</p><p className="mt-2 text-xs text-slate-500">Creator approval: {content.creator?.creatorApprovalStatus || "—"} · Account: {content.creator?.status || "—"}</p><div className="mt-2 flex gap-3 text-xs font-bold"><Link className="text-orange-600" to={`/creators/${content.creator?.username}`}>Public profile</Link><Link className="text-slate-600" to="/admin/creators">Admin creators</Link></div></div></div>{profile?.bio ? <p className="mt-4 text-sm text-slate-600">{profile.bio}</p> : null}</section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Description and body</h2><div className="mt-4 space-y-5"><div><h3 className="text-xs font-bold uppercase text-slate-400">Description</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{content.description || "No description supplied."}</p></div>{content.contentType === "TEXT" ? <div><h3 className="text-xs font-bold uppercase text-slate-400">Text body</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{content.body}</p></div> : null}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Media</h2><p className="mt-1 text-xs text-slate-500">Previews use only delivery data supplied by the admin API.</p><div className="mt-5"><AdminContentMediaPreview content={content} /></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Access preview</h2><div className={`mt-4 flex gap-3 rounded-xl p-4 text-sm ${content.accessLevel === "PUBLIC" ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-800"}`}>{content.accessLevel === "PUBLIC" ? <FiCheckCircle /> : <FiLock />}<p>{accessCopy}</p></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Review history</h2><div className="mt-5">{history.isLoading ? <Loader label="Loading content history..." /> : history.isError ? <p className="text-sm text-red-600">Unable to load history.</p> : <ContentHistoryTimeline history={history.data} />}</div></section></div>
      <aside className="space-y-6 xl:sticky xl:top-24 xl:h-fit"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Manual review checklist</h2><p className="mt-1 text-xs text-slate-500">Admin assistance only. It never authorizes or performs approval.</p><div className="mt-5 space-y-2">{checklistItems.map((item) => <label className="flex items-start gap-3 rounded-xl border border-slate-200 p-3 text-sm" key={item}><input checked={Boolean(checklist[item])} className="mt-1 accent-emerald-600" disabled={!canDecide} onChange={(event) => setChecklist((current) => ({ ...current, [item]: event.target.checked }))} type="checkbox" /><span>{item}</span></label>)}</div><p className={`mt-4 rounded-xl p-3 text-xs font-bold ${checklistComplete ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{checklistComplete ? "Checklist complete. Approval confirmation is available." : "Complete all checks to enable approval."}</p></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Moderation metadata</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs uppercase text-slate-400">Creator-visible feedback</dt><dd className="mt-1 whitespace-pre-wrap">{content.creatorFeedback || "—"}</dd></div><div><dt className="text-xs uppercase text-slate-400">Internal note</dt><dd className="mt-1 whitespace-pre-wrap">{content.internalModerationNote || "—"}</dd></div><div><dt className="text-xs uppercase text-slate-400">Reviewed by</dt><dd>{content.reviewedBy?.name || content.reviewedBy?.username || content.reviewedBy || "—"}</dd></div><div><dt className="text-xs uppercase text-slate-400">Reviewed at</dt><dd>{date(content.reviewedAt)}</dd></div><div><dt className="text-xs uppercase text-slate-400">Status version</dt><dd>{content.statusVersion ?? "—"}</dd></div>{content.stateSyncPending ? <div className="rounded-xl bg-amber-50 p-3 text-amber-700"><FiClock className="inline" /> Synchronization is pending.</div> : null}</dl></section></aside></div>
    <ContentDecisionModal checklistComplete={checklistComplete} isOpen={Boolean(modal)} mode={modal} onClose={() => !submitting && setModal("")} onSubmit={decide} submitting={submitting} />
  </div>;
}
