import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FiCheckCircle, FiRefreshCw, FiShield, FiXCircle } from "react-icons/fi";
import Loader from "../../components/common/Loader";
import { verifiedCreatorService } from "../../services/verifiedCreatorService";

const states = ["", "PENDING", "APPROVED", "REJECTED", "EXPIRED"];

export default function VerifiedCreatorManagementPage() {
  const client = useQueryClient();
  const [status, setStatus] = useState("");
  const [message, setMessage] = useState("");
  const [planAmount, setPlanAmount] = useState("");
  const [error, setError] = useState("");
  const query = useQuery({ queryKey: ["admin", "verified-creators", status], queryFn: () => verifiedCreatorService.listAdmin(status).then((r) => r.data.data) });
  const decision = useMutation({ mutationFn: ({ id, action }) => verifiedCreatorService[action](id, { creatorMessage: message }), onSuccess: () => { setMessage(""); setError(""); client.invalidateQueries({ queryKey: ["admin", "verified-creators"] }); }, onError: (e) => setError(e.response?.data?.message || "Unable to save the decision.") });
  const savePlan = useMutation({ mutationFn: () => verifiedCreatorService.updatePlan(Number(planAmount || query.data?.plan?.starsPerMonth)), onSuccess: (response) => { setPlanAmount(String(response.data.data.plan.starsPerMonth)); setError(""); client.invalidateQueries({ queryKey: ["admin", "verified-creators"] }); client.invalidateQueries({ queryKey: ["creator", "verified-status"] }); }, onError: (e) => setError(e.response?.data?.message || "Unable to update the monthly price.") });
  const items = query.data?.items || [];
  return <main className="mx-auto max-w-6xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-orange-500">Trust and subscriptions</p><h1 className="mt-1 text-3xl font-black">Verified Creators</h1><p className="mt-2 text-sm text-slate-500">Review blue-tick applications and monitor monthly status.</p></div><button className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold" onClick={() => query.refetch()} type="button"><FiRefreshCw /> Refresh</button></header>
    <div className="mt-6 flex flex-wrap gap-2">{states.map((item) => <button className={`rounded-full px-4 py-2 text-xs font-bold ${status === item ? "bg-slate-900 text-white" : "border border-slate-200 bg-white text-slate-600"}`} key={item || "ALL"} onClick={() => setStatus(item)} type="button">{item || "ALL"}</button>)}</div>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[.14em] text-orange-500">Plan settings</p><div className="mt-3 flex flex-wrap items-end gap-3"><label className="text-sm font-bold text-slate-700">Monthly Verified Creator price<span className="mt-1 flex items-center overflow-hidden rounded-xl border border-slate-200"><input className="w-36 px-3 py-2.5 outline-none" min="1" max="1000000" onChange={(e) => setPlanAmount(e.target.value)} placeholder={String(query.data?.plan?.starsPerMonth || 190)} step="1" type="number" value={planAmount} /><span className="border-l border-slate-200 bg-slate-50 px-3 py-2.5 text-slate-500">Stars</span></span></label><button className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50" disabled={savePlan.isPending} onClick={() => savePlan.mutate()} type="button">{savePlan.isPending ? "Saving..." : "Save price"}</button></div><p className="mt-3 text-xs text-slate-500">The new amount applies to new applications. Existing subscriptions retain the price they accepted.</p></section>
    {error ? <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}
    {query.isLoading ? <div className="mt-8"><Loader label="Loading Verified Creator applications..." /></div> : null}
    {!query.isLoading && !items.length ? <div className="mt-6 grid min-h-56 place-items-center rounded-2xl border border-slate-200 bg-white"><div className="text-center text-slate-500"><FiShield className="mx-auto text-4xl text-slate-300" /><p className="mt-3 font-bold">No applications found</p></div></div> : null}
    <div className="mt-6 grid gap-4">{items.map((item) => <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" key={item.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-black">{item.creator?.name || "Unknown creator"}</h2><p className="text-sm text-slate-500">@{item.creator?.username} · {item.creator?.email}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{item.status}</span></div><p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-700">{item.statement || "No statement supplied."}</p><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-500"><span>{item.starsPerMonth || 190} Stars / month</span><span>Payment: {item.paymentStatus}</span><span>Ends: {item.currentPeriodEnd ? new Date(item.currentPeriodEnd).toLocaleDateString() : "—"}</span></div>{item.status === "PENDING" ? <div className="mt-4"><input className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" onChange={(e) => setMessage(e.target.value)} placeholder="Optional message to creator" value={message} /><div className="mt-3 flex gap-2"><button className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50" disabled={decision.isPending} onClick={() => decision.mutate({ id: item.id, action: "approve" })} type="button"><FiCheckCircle /> Approve verified</button><button className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50" disabled={decision.isPending} onClick={() => decision.mutate({ id: item.id, action: "reject" })} type="button"><FiXCircle /> Reject</button></div></div> : null}</article>)}</div>
  </main>;
}
